### ISSUE TITLE
Migrate to TypeScript and Next.js

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/fosscu.org#117]
It need to be discussed, I happy to discuss on this issue.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/FOSS-Community) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/FOSS-Community/website-fossc/issues/117">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/FOSS-Community/website-fossc/issues/117/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/FOSS-Community/website-fossc/issues/117/pledge.svg">
</picture>
</a>

**Comment by Yash-Var** [comment]
@Mr-Sunglasses ready..

**Comment by Bharadwajshivam28** [comment]
> It need to be discussed, I happy to discuss on this issue.

We can go with it sir

**Comment by vivekpal1** [comment]
@Mr-Sunglasses Sir, Can I help on this migrating the project to next-13 turbo?

**Comment by vivekpal1** [comment]
> It need to be discussed, I happy to discuss on this issue.

What we can do is,
just make different pages on this template that @akshatcoder-hash created, https://github.com/FOSS-Community/Community-Hub
it would be easier and also uniform design would be maintained all over docs and landing page :)
We need to tweak some, components and CSS stuff and colorise it green 💚

**Comment by akshatcoder-hash** [comment]
@vivekpal1 Those pages can be maintained for Community Guidelines and stuff. We need a landing page with less of text information.

**Comment by Mr-Sunglasses** [comment]
Added Bounty of $30 for this issue.

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses & @akshatcoder-hash sir I would love to work on it . Please assign this to me...

@codecShivam  To avoid ambiguity, this issue is not assigned to anyone currently so is available to anyone. Submit a draft PR getting started on the work and we can assign it.

**Comment by codecShivam** [comment]
> > @Mr-Sunglasses & @akshatcoder-hash sir I would love to work on it . Please assign this to me...
> 
> @codecShivam To avoid ambiguity, this issue is not assigned to anyone currently so is available to anyone. Submit a draft PR getting started on the work and we can assign it.

Okay sir, will create a draft pr in few days..

**Comment by harsh0728** [comment]
Can you assign this issue to me I can help me in resolving this issue
