### ISSUE TITLE
Add Toggle Theme Functionality

### ISSUE THREAD

**Issue by Saurav-Pant** [FOSS-Community/fosscu.org#134]
As a user, I want to be able to switch between light and dark themes on the website/app, so that I can choose the one that is easier on my eyes or fits my preferences.

To implement this feature, we will need to add a button or switch somewhere on the page that the user can click or tap to toggle the theme. When the user switches the theme, we will need to update the CSS styles accordingly to apply the appropriate colors, fonts, and other design elements.

In addition, we should consider storing the user's preference for the theme in a cookie or local storage, so that it persists across page reloads and sessions.

By adding this functionality, we can improve the user experience and make the website/app more accessible and customizable for our users.

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue, assign me this issue

**Comment by YASH-YADAV-dynamo** [comment]
i really want to work on this issue, i have done it previously, please assign me this issue

**Comment by draunger** [comment]
@Saurav-Pant I want to work on this

**Comment by Mr-Sunglasses** [comment]
@draunger yeah you can :)

**Comment by draunger** [comment]
@Saurav-Pant can I use normal css for toggle button instead of tailwind css ??

**Comment by draunger** [comment]
@Saurav-Pant can I use normal css for toggle button instead of tailwind css ??

**Comment by Mr-Sunglasses** [comment]
Hey 👋 @draunger if you can do in Normal css I think it isn't hard for you to learn to do it with Tailwindcss

**Comment by draunger** [comment]
@Mr-Sunglasses as I have done the this issue using normal css, if you agree I will send the PR of this issue 
Else
I will take some time using tailwind css

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses as I have done the this issue using normal css, if you agree I will send the PR of this issue Else I will take some time using tailwind css

@draunger As we use tailwind everywhere so take your time and come back when you are comfortable with TailwindCSS :-)

**Comment by draunger** [comment]
@Mr-Sunglasses ok sir

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses as the issue said that we have to make toggle button for dark them but the website is already in dark so there is no need for button right ?? 

It's a good pick @draunger , As we have our main theme in Green and dark so no need for this feature to implement.

**Comment by draunger** [comment]
@Mr-Sunglasses so we have to close this issue?

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses so we have to close this issue? 

Yeah I already closed it as completed.
