### ISSUE TITLE
[Feature]: Integrate Dependabot for Automated Dependency Updates

### ISSUE THREAD

**Issue by harmeetsingh11** [FOSS-Community/fosscu.org#238]
### Describe the feature you'd like to request

Keeping the project's dependencies up to date can be a challenging task, especially when done manually. To streamline and automate this process, we propose integrating Dependabot.

### Describe the solution you'd like

We need to add Dependabot to our project as it will significantly aid in keeping our dependencies current. Once activated, Dependabot will automatically submit pull requests (PRs) whenever there are outdated dependencies identified in our `package.json` file.

This automated approach will enhance our project's stability, security, and overall maintenance by ensuring that we are always using the latest and most secure versions of our dependencies.

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a IWOC24 contributor
- [X] I want to work on this issue

**Comment by harsh0728** [comment]
Hey Can you assign this to me I will try to solve this

**Comment by SOHAIB-code-png** [comment]
These are my key idea/approach towards the solution of this issue:  


- **Setting  up Dependabot**: Add a `.github/dependabot.yml` file to configure automatic dependency updates.
  
- **Defining  update schedule** : Decide on how often updates should be checked (daily, weekly, etc.).

- **Automate PRs**: Allow Dependabot to submit pull requests whenever an outdated dependency is detected.

Please assign me this issue and add a tag of hacktoberfest
