### ISSUE TITLE
[Bug]: Unnecessary console statements

### ISSUE THREAD

**Issue by JiyaGupta-cs** [FOSS-Community/fosscu.org#344]
### What happened?

Unnecessary console statements
The console should be kept clean
![image](https://github.com/user-attachments/assets/70a71947-7569-415b-bd52-fd3deefe6ccb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harsh0728** [comment]
I can make it correct Please assign this issue to me so that i can resolve this quickly
