### ISSUE TITLE
[Bug]: Unable to submit the contact form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [FOSS-Community/fosscu.org#345]
### What happened?

 Unable to submit the contact form
![image](https://github.com/user-attachments/assets/0583c2d5-c729-49f7-9041-0b8cd669778d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haxshith** [comment]
please assign me the issue so that I can try and work on it :)

**Comment by JiyaGupta-cs** [comment]
Hey @haxshith this has already been fixed in the PR
You can try fixing some other issues

**Comment by haxshith** [comment]
okayy

**Comment by Mr-Sunglasses** [comment]
close : #350
