### ISSUE TITLE
[Bug]: Navbar Title Overflow in Mobile View

### ISSUE THREAD

**Issue by Mefisto04** [FOSS-Community/fosscu.org#363]
### Contact Details

kawalemayur30@gmail.com

### What happened?

The title in the navbar is overflowing and going outside the sidenav in mobile view. This results in a poor user experience and makes navigation difficult.
This is the attacked screenshot:
![image](https://github.com/user-attachments/assets/aeb29599-9ec1-4677-9951-eae991e7488b)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
N/A,
I expected the navbar title to fit within the sidenav, ensuring that all content is visible without overflow.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nikkvijay** [comment]
I want to work on this issue , can you please assign me.
